name: Build and Push Docker Image

on:
  push:
    branches:
      - workflow  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - v2.0  # Optional: Run the workflow on PRs target

jobs:
  build-and-push:
    runs-on: image-builder

    permissions:
      contents: read
      packages: write  # Required to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/debian.dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}:2.0